### ISSUE TITLE
A possible out-of-range of array in pierc_new_n.f in Section003

### ISSUE THREAD

**Issue by SuwenJunliu** [georom1996/GCSRF_GIG_USTC-Training-Package#1]
There might be a possible out-of-range of the array **inn1** in pierc_new_n.f: 297 line.

# Symptom

1. run the Python script according to README.md in Section003 folder, the invalid memory access error message might show in the terminal. 
2. recompile the Fortran program with options -fbound-check and -g, the program will show the out-of-range of the array **inn1** in pierc_new_n.f: 297

# Analysis

It might cause by the uninitialized array **lensta**. This variable will be assigned by  ``` lensta(nums0)=ldir2 ``` in pierc_new_n.f: 161, but somehow the index **nums** in pierc_new_n.f: 296 will exceed the number of total stations. The length of **lensta** is 50, which will leave the trash data (a large number or a negative) if it is uninitialized. 

# Quick fix

initialize the array **lensta** at the beginning of this problem:
```
	do i=1,nstamax
            lensta(i) = 0
	enddo
```

**Comment by georom1996** [comment]
## Reply :
* #1
* Thank you for your issue posted here. As you can see, the source code of PSDM comes entirely from Prof. Chen Ling and her group, so we did not modify any of the source code when performing our migration tests. In fact, tests on laptops in my group never encounter the same 'memory access error'. 
* However, as this issue is potentially significant on some other devices and platforms, initialising 'lensta' should be safer and more necessary. I have modified 'pierc_new_n.f' as you suggested.

## Bugfix :
Add lines to 'pierc_new_n.f'.

```
	! issue posted by Junliu Suwen >>>
	do i=1,nstamax
		lensta(i) = 0
	enddo
	! issue posted by Junliu Suwen <<<
```
